
var languageCode = {
    '38': 'plain_text',
    '11': 'c_cpp',
    '44': 'c_cpp',
    '63': 'c_cpp',
    '40': 'sql',
    '2': 'pascal',
    '22': 'pascal',
    '10': 'java',
    '25': 'plain_text',
    '27': 'csharp',
    '30': 'plain_text',
    '23': 'plain_text',
    '13': 'assembly_x86',
    '20': 'd',
    '5': 'plain_text',
    '47': 'plain_text',
    '7': 'ada',
    '28': 'batchfile',
    '3': 'perl',
    '4': 'python',
    '17': 'ruby',
    '26': 'lua',
    '16': 'plain_text',
    '19': 'plain_text',
    '29': 'php',
    '33': 'scheme',
    '18': 'scheme',
    '31': 'lisp',
    '32': 'lisp',
    '39': 'scala',
    '36': 'erlang',
    '21': 'haskell',
    '8': 'ocaml',
    '14': 'plain_text',
    '15': 'prolog',
    '6': 'plain_text',
    '12': 'plain_text',
    '9': 'plain_text',
    '62': 'text',
    '54': 'perl',
    '111': 'clojure',
    '114': 'golang',
    '116': 'python',
    '124': 'plain_text',
    '35': 'javascript',
    '56': 'javascript',
    '99': 'python',
    '109': 'python',
    '85': 'swift',
    '93': 'rust',
    '97': 'scheme',
    '117': 'r',
    '118': 'cobol',

}

var URL = {
    run: '/api/ide/run/all',
    submit: '/api/ide/submit'
} 